import { getSession } from "@/features/auth/domain/usecase/server";
import { LoadingProvider } from "@/features/loading/view/provider";
import { getTheme } from "@/features/theme/domain/usecase/server";
import type { Metadata } from "next";
import "./globals.css";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: { children: React.ReactNode }) {
  const user = await getSession();
  console.log("layout currentUser", user);
  const theme = getTheme();
  return (
    <html lang="ja" data-theme={theme}>
      <body>
        <LoadingProvider>{children}</LoadingProvider>
      </body>
    </html>
  );
}
