import SideMenu from "@/components/layouts/SideMenu";
import { LoadingProvider } from "@/features/loading/view/provider";
import { getTheme } from "@/features/theme/domain/usecase/server";
import type { Metadata } from "next";
import "./globals.css";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: { children: React.ReactNode }) {
  const theme = getTheme();
  return (
    <html lang="ja" data-theme={theme}>
      <body>
        <LoadingProvider>
          <div className="flex min-h-screen">
            <SideMenu />
            <main className=" flex-1">{children}</main>
          </div>
        </LoadingProvider>
      </body>
    </html>
  );
}
